### ISSUE TITLE
Multi-label domains not working

### ISSUE THREAD

**Issue by isjwuk** [microsoft/SharePoint-Embedded-VS-Code-Extension#13]
Using this with a multi-label domain (for example myorg.ac.uk) rather than a shorter myorg.com doesn't work for me and fails when creating the Trial Container Type. This type of domain uses the SharePoint admin address myorgac-admin.sharepoint.com  but the plugin tries to find myorg-admin.sharepoint.com and then fails.

There is a section in Account.ts login() that reads
```
                const parts = tenantDomain.split('.');
                domain = parts[0];
```

Is this the cause? it's only grabbing the first part of the domain name ("myorg") and ignoring any subsequent parts ("ac")

**Comment by therealAJ** [comment]
@isjwuk thanks for raising this issue! You're right in that part of code being the issue for domains that contain subdomains. The fix requires switching to a different API call that requires a 1P pre-authorization Graph scope, so I'll start that process and keep this thread updated about pushing up a fix.

**Comment by therealAJ** [comment]
@isjwuk this should have been fixed in the March release, are you still running into this issue, or can I close this issue?

**Comment by therealAJ** [comment]
@isjwuk, the latest version of the Extension should address this issue, can you double check you're unblocked? If so, I'll close this issue.

**Comment by isjwuk** [comment]
Thanks @therealAJ - I ended up with a manual workaround and am now on another project so don't have the bits handy to test any more. Good to fix for the next person who tries this though.
