### ISSUE TITLE
Extension <seems> to use custom domain, not tenant ID, when creating Container Type

### ISSUE THREAD

**Issue by andrewconnell** [microsoft/SharePoint-Embedded-VS-Code-Extension#17]
When signing in to an M365 tenant that uses a custom domain, the extension *seems* to use that domain from the login to determine the tenant ID... but that's not correct.

As shown in the following screenshot, I'm logging in with a tenant admin primary/default domain (`andrewconnell.com`) on my tenant... but this is not my tenantid. You can see from the error in the lower-right, that's what the extension is using for my tenant ID to get the SPO admin URL. That is not correct... my tenant ID is something completely different.

![vse-error](https://github.com/microsoft/SharePoint-Embedded-VS-Code-Extension/assets/2068657/715bd042-6a9e-4bbb-b584-e41788092f87)

## Workaround

If I sign in using the same account, but using the native address for this account (`alias@tenantid.onmicrosoft.com`), it works.

**Comment by therealAJ** [comment]
@andrewconnell this should be fixed in the latest version of the extension. Can you report back and I'll close this if resolved!

**Comment by therealAJ** [comment]
I'll close this issue for now, please re-open if you're still having issues!
