### ISSUE TITLE
 'vscode.spe-authentication" not found

### ISSUE THREAD

**Issue by MKP365** [microsoft/SharePoint-Embedded-VS-Code-Extension#21]
Type: <b>Bug</b>

When i tried to login to SP embedded account throws error "Unable to install extension 'vscode.spe-authentication' because it is not found." and not working properly. did multiple time reinstallation but nothing changed

Extension version: 0.0.4
VS Code version: Code 1.89.0 (b58957e67ee1e712cebf466b995adf4c5307b2bd, 2024-05-01T02:09:22.859Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 3500U w/ Radeon Vega Mobile Gfx (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.88GB (4.67GB free)|
|Process Argv|--crash-reporter-id f1f1d8cb-70e3-4e7b-b698-22ac85dd8089|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31018788
dsvsc021:30996838
724cj586:31013169
a69g1124:31038041
pythonprc:31039816
dwnewjupytercf:31039676

```

</details>

**Comment by mbielanczuk** [comment]
Same here: 'Unable to install extension 'vscode.spe-authentication' because it is not found.'
Extension version: 0.0.4
VS Code version: Code 1.89.1

**Comment by yborghmans** [comment]
Same here, I just downgraded to the previous version.

**Comment by MKP365** [comment]
i have downgraded to previous version but still error persists 🤷


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by therealAJ** [comment]
Hey everyone, this will be addressed in the next release of the extension coming within the next few weeks. In the meanwhile, this should be a transient issue that doesn't block any extension functionality (ie you should be able to dismiss the error and continue with development).

**Comment by therealAJ** [comment]
Hey everyone, this should be fixed in the latest version. I'll close this for now, but please report any other found issues!
